# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Research @ Mangaki
tagline:             'Recommandation d''anime et de mangas'
description:         'Nous cherchons à faire émerger par les algorithmes des pépites de la culture japonaise.</p><p>Ce blog permet de rendre compte de nos découvertes.</p><p>Testez <a href="http://mangaki.fr">Mangaki</a> ou <a href="https://github.com/mangaki/mangaki/">forkez-nous</a>.'
url:                 http://research.mangaki.fr
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jill-Jênn Vie
  url:               https://twitter.com/mangaki
  email:             jj@mangaki.fr

github:
  repo:              https://github.com/mangaki/mangaki/

# Custom vars
version:             1.0.0
